[package]
name = "coreutils"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.bloat]
inherits = "release"
strip = false

[dependencies]
rustix = { version = "1.0.7", features = ["system"] }
