[build]
rustflags = [
    "-C",
    "linker-plugin-lto",
    "-C",
    "link-arg=-Wl,-z,pack-relative-relocs",
    "-C",
    "link-arg=-Wl,-O1",
    "-C",
    "link-arg=-Wl,--gc-sections",
    "-C",
    "link-arg=-Wl,--as-needed",
    "-C",
    "link-arg=-Wl,-z,now",
    "-C",
    "link-arg=-Wl,-z,relro",
]
